import React from "react";
import { Grid, } from "@material-ui/core";

const Service7 = () => {
  return (
    <div className="section section-service7 bg-light-gray" id="service7">
      <div className="container">
        <Grid container alignItems="center" spacing={5}>
          <Grid item lg={6} md={6} sm={12} xs={12}>
            <div className="max-w-372 text-left">
              <h2 className="mb-4">How can boneage.com help you?</h2>
              <p className="whitespace-pre-wrap">
                {`Boneage.com Artificial Intelligence(AI) utilizes TW3(Tanner-Whitehouse, third edition) which analyzes the growth factor of 13 bones in the hand and wrist and results in a skeletal maturity score(SMS)
              \nThe Tanner-Whitehouse method is a bone-specific scoring technique in which a numerical score is assigned to selected hand-wrist bones depending on the appearance of certain well defined maturity indicators.
\n13 bones including the radius, ulna and short bones of the thumb, middle and little fingers.  Each of the bones that is being evaluated is compared to a standard set of bones at different stages of maturation. A score is assigned to each bone based on maturation and sex of the patient.  Once all the bones have been scored, a total score is generated by adding all bone scores together and then plotted on a graph to determine how the bone age relates to the chronological age.
`}
              </p>
            </div>
          </Grid>
          <Grid item lg={6} md={6} sm={12} xs={12}>
            <img
              className="max-h-280"
              src="./assets/images/x-ray2.png"
              alt="analyze"
            />
          </Grid>
        </Grid>
      </div>
    </div>
  );
};

export default Service7;
